name: Deploy Nuxt site to myServerOmiCode

on:
  push:
    branches: ["master"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: npm install
      - name: Static HTML export with Nuxt
        run: npm run generate
      - name: Copy built source
        run: cp -r dist/* /www/wwwroot/grutech.edu.vn/
